server:
  port: 8081

spring:
  application:
    name: matching-engine
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

matching:
  orderbook:
    bootstrap:
      orders-per-symbol: 10
      price-step-ratio: 0.001
